package repositories

import (
	"context"
	"errors"
	"fmt"

	"gorm.io/gorm"

	"ryze/backend/models"
)

// ErrTestSessionNotFound indicates the test session does not exist or is no
// longer active (soft-deleted or unknown token hash).
var ErrTestSessionNotFound = errors.New("test session not found")

// TestSessionRepository defines the data-access operations for Test Mode
// sessions. Only the hashed opaque token is ever queried; the raw bearer token
// never reaches this layer.
type TestSessionRepository interface {
	Create(ctx context.Context, session *models.TestSession) error
	FindActiveByTokenHash(ctx context.Context, tokenHash string) (*models.TestSession, error)
	SoftDelete(ctx context.Context, id string) error
}

type testSessionRepository struct {
	db *gorm.DB
}

func NewTestSessionRepository(db *gorm.DB) TestSessionRepository {
	return &testSessionRepository{db: db}
}

// Create persists a new test session. A duplicate token hash is an integrity
// failure and is not expected: tokens are generated by the service with full
// entropy.
func (r *testSessionRepository) Create(ctx context.Context, session *models.TestSession) error {
	if err := r.db.WithContext(ctx).Create(session).Error; err != nil {
		return fmt.Errorf("failed to create test session: %w", err)
	}
	return nil
}

// FindActiveByTokenHash returns the active (non-deleted) test session matching
// the hashed token, or ErrTestSessionNotFound when none is active.
func (r *testSessionRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string) (*models.TestSession, error) {
	var session models.TestSession
	if err := r.db.WithContext(ctx).
		First(&session, "token_hash = ?", tokenHash).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrTestSessionNotFound
		}
		return nil, fmt.Errorf("failed to find test session: %w", err)
	}
	return &session, nil
}

// SoftDelete ends an active test session. The row is never physically removed
// so the exit event remains auditable; GORM's DeletedAt handling excludes it
// from every active query.
func (r *testSessionRepository) SoftDelete(ctx context.Context, id string) error {
	result := r.db.WithContext(ctx).Delete(&models.TestSession{}, "id = ?", id)
	if result.Error != nil {
		return fmt.Errorf("failed to soft delete test session: %w", result.Error)
	}
	if result.RowsAffected == 0 {
		return ErrTestSessionNotFound
	}
	return nil
}